### PR TITLE
Workers Assets Binding

### LINKED ISSUE #644: Introduce Workers Assets binding
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Allow access to static assets from user worker.

### PR DESCRIPTION
**Pull request by BrandonDyer64**
closes #644 

I went down a rabbit hole creating an entire new `Assets` env binding just to find out it's a `Fetcher`. In fact, you can use assets without this PR by just calling `env.get_binding::<Fetcher>("ASSETS")`.

Testing:
- Run `npx wrangler dev` in `worker-sandbox`
- Go to `/asset/test.txt`
- See `TEST` in browser
- Go to `/asset/doesnotexist.txt`
- See 404

### CODE REVIEW

**Comment by BrandonDyer64** [comment]
Maybe this isn't enough. I'm doing some testing and setting the following in my `wrangler.toml` will serve the assets, but not expose the binding:
```toml
[assets]
binding = "ASSETS"
directory = "./public/"
```
There's nothing related to assets in the "Your worker has access to the following bindings:" readout.

**Comment by kflansburg** [comment]
Sorry that you went in circles on this. I think this looks correct. Have you tried deploying your worker and testing that? I will see if I can reproduce the issue in local development.

**Comment by kflansburg** [comment]
This worked locally for me. You do need to specify a dummy URL (I think all Fetchers behave this way).

**Comment by BrandonDyer64** [comment]
> You do need to specify a dummy URL

Ah, that was it. Adding `https://example.com` to the beginning of my URL fixed it for me.

**Comment by BrandonDyer64** [comment]
Couple questions/feedback on this:

1. I don't see the `ASSETS` binding in the `Your worker has access to the following bindings:` printout. That seems like a bug, and it's why it took me so long to find a solution. I was chasing ghosts.
2. What's your recommendation for getting the `fetch()` response body as bytes? I had to import `http_body_util::BodyExt` and write this, just to get basic data out:
    - ```rust
      let bytes: Vec<u8> = response.into_body().collect().await?.to_bytes().to_vec();
      ```

**Comment by kflansburg** [comment]
> Couple questions/feedback on this:
> 
> 1. I don't see the `ASSETS` binding in the `Your worker has access to the following bindings:` printout. That seems like a bug, and it's why it took me so long to find a solution. I was chasing ghosts.
> 2. What's your recommendation for getting the `fetch()` response body as bytes? I had to import `http_body_util::BodyExt` and write this, just to get basic data out:
>    
>    * ```rust
>      let bytes: Vec<u8> = response.into_body().collect().await?.to_bytes().to_vec();
>      ```

I think 1. may be a bug in `wrangler` cc @petebacondarwin 

For 2, I assume you are using the `http` crate feature? I think the main way to consume it is as a stream like you are doing, but I suppose we could add some utility methods to the concrete [`Body`](https://github.com/cloudflare/workers-rs/blob/636d76047fb41076de0f648ddb57c5f192bedbb0/worker/src/http/body.rs#L24) type you get from our `Fetcher::fetch`.

**Comment by BrandonDyer64** [comment]
> we could add some utility methods to the concrete [`Body`](https://github.com/cloudflare/workers-rs/blob/636d76047fb41076de0f648ddb57c5f192bedbb0/worker/src/http/body.rs#L24) type you get from our `Fetcher::fetch`

I'd love to see an `async fn to_bytes() -> Vec<u8>` and `async fn to_json<T>() -> T` on `Body` if possible. It would make life a lot easier.

**Comment by BrandonDyer64** [comment]
I'm not sure why the tests are failing in the CI. Started happening after my first commit, which just added a single method to `Env`.

**Comment by BrandonDyer64** [comment]
Can anyone review this?

**Comment by kflansburg** [comment]
I'm no longer with Cloudflare, so I cannot approve. I think test failures are related to the Rust 1.82 issue [here](https://github.com/cloudflare/workers-rs/issues/668). We may need to pin the Rust version in our CI. 

Otherwise, I think this is a good test to add. I would like to see it also tested with `http` flag enabled, we are trying to keep those two test suites identical and will probably eventually make `http` the default (or at least that was my original plan). 

cc @harrishancock

**Review by zebp — APPROVED** [review]
Sorry for the delay! It'd be nice to have this tested but otherwise LGTM, I'm going to merge into a non-main branch so I can add tests and update miniflare since I think the testing for this might be a bit more involved than the scope of this PR.

**Pull request merged**
