### PR TITLE
Allow usage of http::{Request, Response} for `fetch` handlers

### PR DESCRIPTION
**Pull request by fisherdarling**
This PR adds a conversion from `worker_sys::Request` to `http::Request<ByteStream>` and from `http::Request<http_body::Body + 'static>` to `worker::Response`.

This PR is more of an MVP and not necessarily as ergonomic / well-written as it should be. I don't think this should be merged as-is, however I think it's a good starting point to discuss the best way to add this.

This actually only pulls in one extra crate, `http_body`. If none of the http conversion code is used, I do not believe this will lead to any increase in code size.

Here's some example code that can be written with this work:

```rust
#[event(fetch, respond_with_errors, http)]
pub async fn main(
    req: worker::HttpRequest,
    _env: worker::Env,
    _ctx: worker::Context,
) -> Result<axum::response::Response> {
    use tower_service::Service;

    let mut app: axum::Router<_> =
        axum::Router::new().route("/", axum::routing::get(|| async { "Hello, World!" }));

    app.call(req)
        .await
        .map_err(|e| worker::Error::from(e.to_string()))
}
```

I did not define a `worker::HttpResponse` since most responses are very generic, and most responses are `http::Response`s with bodys that impl [http_body::Body](https://docs.rs/http-body/latest/http_body/trait.Body.html).

### CODE REVIEW

**Comment by fisherdarling** [comment]
@zebp I'm going to close this for now and just keep developing on my fork. I've been successfully this fork on my local project, but there have been some snags (mainly `Send + Sync` bounds). I'll resubmit once I have something cleaner.

Though I can re-open and leave the PR here if you want (for visibility maybe?).

**Comment by kpietraszko** [comment]
@fisherdarling Any news on this?

**Comment by kpietraszko** [comment]
If anyone tries to use this branch, remember to add `compatibility_flags = ["streams_enable_constructors"]` to your wrangler.toml. I've spent an embarrassing amount of time figuring this out.

**Comment by fisherdarling** [comment]
@kpietraszko I don't have the time to work on this anymore :/ maybe in a few months, but it will be a while. I'm glad you found that issue though! That sounds annoying.

**Comment by makorne** [comment]
> If anyone tries to use this branch, remember to add `compatibility_flags = ["streams_enable_constructors"]` to your wrangler.toml. I've spent an embarrassing amount of time figuring this out.

@kpietraszko  Thanks for sharing this issue! 
But  how do you solve socket2 compiling error with feat/optional-tokio branch?
 I tried many socket2 versions with such a result:
```
error[E0308]: mismatched types
    --> /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/socket.rs:1902:15
     |
1902 | from!(Socket, net::TcpListener);
     |               ^^^^^^^^^^^^^^^^ expected struct `TcpListener`, found `()`
     |
    ::: /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/lib.rs:104:16
     |
104  |             fn from(socket: $from) -> $for {
     |                ---- implicitly returns `()` as its body has no tail or `return` expression

error[E0308]: mismatched types
    --> /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/socket.rs:1903:15
     |
1903 | from!(Socket, net::UdpSocket);
     |               ^^^^^^^^^^^^^^ expected struct `UdpSocket`, found `()`
     |
    ::: /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/lib.rs:104:16
     |
104  |             fn from(socket: $from) -> $for {
     |                ---- implicitly returns `()` as its body has no tail or `return` expression

Some errors have detailed explanations: E0061, E0308, E0412, E0422, E0425, E0432, E0433, E0583.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `socket2` due to 200 previous errors 
```

**Comment by kpietraszko** [comment]
@makorne I don't know, sorry. I'd recommend using a reverse `cargo tree` to find out why socket2 is referenced in the first place, maybe it shouldn't be.

**Comment by makorne** [comment]
> cargo tree

```
── axum v0.5.7 (https://github.com/kpietraszko/axum.git?branch=feat/optional-tokio#a85b7cc6)
│   ├── async-trait v0.1.58 (proc-macro)
│   │   ├── proc-macro2 v1.0.47
│   │   │   └── unicode-ident v1.0.5
│   │   ├── quote v1.0.21
│   │   │   └── proc-macro2 v1.0.47 (*)
│   │   └── syn v1.0.103
│   │       ├── proc-macro2 v1.0.47 (*)
│   │       ├── quote v1.0.21 (*)
│   │       └── unicode-ident v1.0.5
│   ├── axum-core v0.2.5 (https://github.com/kpietraszko/axum.git?branch=feat/optional-tokio#a85b7cc6)
│   │   ├── async-trait v0.1.58 (proc-macro) (*)
│   │   ├── bytes v1.2.1
│   │   ├── futures-util v0.3.25
│   │   │   ├── futures-core v0.3.25
│   │   │   ├── futures-io v0.3.25
│   │   │   ├── futures-macro v0.3.25 (proc-macro)
│   │   │   │   ├── proc-macro2 v1.0.47 (*)
│   │   │   │   ├── quote v1.0.21 (*)
│   │   │   │   └── syn v1.0.103 (*)
│   │   │   ├── futures-sink v0.3.25
│   │   │   ├── futures-task v0.3.25
│   │   │   ├── memchr v2.5.0
│   │   │   ├── pin-project-lite v0.2.9
│   │   │   ├── pin-utils v0.1.0
│   │   │   └── slab v0.4.7
│   │   │       [build-dependencies]
│   │   │       └── autocfg v1.1.0
│   │   ├── http v0.2.8
│   │   │   ├── bytes v1.2.1
│   │   │   ├── fnv v1.0.7
│   │   │   └── itoa v1.0.4
│   │   ├── http-body v0.4.5
│   │   │   ├── bytes v1.2.1
│   │   │   ├── http v0.2.8 (*)
│   │   │   └── pin-project-lite v0.2.9
│   │   └── mime v0.3.16
│   ├── bitflags v1.3.2
│   ├── bytes v1.2.1
│   ├── futures-util v0.3.25 (*)
│   ├── http v0.2.8 (*)
│   ├── http-body v0.4.5 (*)
│   ├── hyper v0.14.22
│   │   ├── bytes v1.2.1
│   │   ├── futures-channel v0.3.25
│   │   │   └── futures-core v0.3.25
│   │   ├── futures-core v0.3.25
│   │   ├── futures-util v0.3.25 (*)
│   │   ├── http v0.2.8 (*)
│   │   ├── http-body v0.4.5 (*)
│   │   ├── httparse v1.8.0
│   │   ├── httpdate v1.0.2
│   │   ├── itoa v1.0.4
│   │   ├── pin-project-lite v0.2.9
│   │   ├── socket2 v0.4.7
│   │   │   └── libc v0.2.137
│   │   ├── tokio v1.21.2
│   │   │   ├── libc v0.2.137
│   │   │   ├── mio v0.8.5
│   │   │   │   ├── libc v0.2.137
│   │   │   │   └── log v0.4.17
│   │   │   │       └── cfg-if v1.0.0
│   │   │   ├── pin-project-lite v0.2.9
│   │   │   └── socket2 v0.4.7 (*)
│   │   │   [build-dependencies]
│   │   │   └── autocfg v1.1.0
```
Any ideas?

**Comment by kpietraszko** [comment]
Oh you're using axum. That's kinda irrelevant to this specific PR, but your problem is caused by axum referencing too many features, either "make" feature of `tower` or "tcp" of `hyper`. This was solved recently with this PR: https://github.com/tokio-rs/axum/pull/1382 
So try updating axum to v0.5.17. If that doesn't work, try changing it reference axum's git (main branch).

**Comment by makorne** [comment]
That works.Thank you!!!!

**Comment by fakeshadow** [comment]
I have a similar setup using `http` crate types. It's not axum but I believe you can use the same pattern on it.
```rust
// convert basic info needed for routing.
let mut new_req = http::Request::new(());
// uri convert.
*new_req.uri_mut() =
    std::str::FromStr::from_str(req.url().unwrap().to_string().as_str()).unwrap_or_default(); 
// method convert.
*new_req.method_mut() = match req.method() {
    Method::Get => http::Method::GET,
    Method::Post => http::Method::POST,
    _ => http::Method::DELETE, // not using these methods so don't care
};

// insert request and context to extension with homebrew unsafe Send/Sync impl. You can probably find crates doing the same job.
new_req.extensions_mut().insert(FakeSync::new(FakeSend::new(req))); 
new_req.extensions_mut().insert(FakeSync::new(FakeSend::new(req)));

// call router service
router.call(new_req).await

// in handler function extract request and context.
async fn handler(req: http::Request<()>) -> Result<Response> {
    let req = req.extensions_mut().remove::<FakeSync<FakeSend<Request>>>().unwrap().into_inner().into_inner();
    let ctx = req.extensions_mut().remove::<FakeSync<FakeSend<Context>>>().unwrap().into_inner().into_inner();
}
```

**Comment by brainstorm** [comment]
> @zebp I'm going to close this for now and just keep developing on my fork. I've been successfully this fork on my local project, but there have been some snags (mainly `Send + Sync` bounds). I'll resubmit once I have something cleaner.
> 
> Though I can re-open and leave the PR here if you want (for visibility maybe?).

Hi @fisherdarling, we are on a similar crossroads where we have to newtype a bunch of worker vs http types in our crates:

https://github.com/umccr/htsget-rs/blob/cloudflare/htsget-cloudflare/src/handlers/mod.rs

It'd be awesome if you could re-open this PR and potentially save us a lot of time :_)

/cc @mmalenic

**Pull request closed without merging**
