### PR TITLE
Add size & type for FormData

### PR DESCRIPTION
**Pull request by tyhi**
This will expose the size & type functions to match how you would use them natively in js/ts workers.

### CODE REVIEW

**Review by zebp — CHANGES_REQUESTED** [review]
My one and only issue with this PR is the return type of `size`, in the real world we're almost always going to want this as a `usize` and I don't think we'll ever run into a situation where size isn't a positive integer.

(sorry this isn't inline, github won't let me add a comment there for some reason)

**Comment by tyhi** [comment]
> My one and only issue with this PR is the return type of `size`, in the real world we're almost always going to want this as a `usize` and I don't think we'll ever run into a situation where size isn't a positive integer.
> 
> (sorry this isn't inline, github won't let me add a comment there for some reason)

Yeah this makes sense to me, my question is just casting it with `as usize` the best way to do this? Like you said there shouldn't be a situation where it would be negative, I just want to make sure I do this the correct way.

Thanks!

**Comment by zebp** [comment]
> > My one and only issue with this PR is the return type of `size`, in the real world we're almost always going to want this as a `usize` and I don't think we'll ever run into a situation where size isn't a positive integer.
> > (sorry this isn't inline, github won't let me add a comment there for some reason)
> 
> Yeah this makes sense to me, my question is just casting it with `as usize` the best way to do this? Like you said there shouldn't be a situation where it would be negative, I just want to make sure I do this the correct way.
> 
> Thanks!

Casting should work fine, worst case is any invalid values turn into a `0`. This should be fine:
```rust
/// Get the file size.
pub fn size(&self) -> usize {
    self.0.size() as usize
}
```

**Comment by tyhi** [comment]
> > > My one and only issue with this PR is the return type of `size`, in the real world we're almost always going to want this as a `usize` and I don't think we'll ever run into a situation where size isn't a positive integer.
> > > (sorry this isn't inline, github won't let me add a comment there for some reason)
> > 
> > 
> > Yeah this makes sense to me, my question is just casting it with `as usize` the best way to do this? Like you said there shouldn't be a situation where it would be negative, I just want to make sure I do this the correct way.
> > Thanks!
> 
> Casting should work fine, worst case is any invalid values turn into a `0`. This should be fine:
> 
> ```rust
> /// Get the file size.
> pub fn size(&self) -> usize {
>     self.0.size() as usize
> }
> ```

Gotcha thanks for the help!

Sorry for the noise, may or may not have delete the fork by accident. #

**Pull request closed without merging**
