### PR TITLE
fix: response body access converting body as string

### LINKED ISSUE #80: Accessing response body forces string conversion
`Response::bytes()` calls `text()` when inner data is `ResponseBody::Streaming` so data gets corrupted with error message.
https://github.com/cloudflare/workers-rs/blob/1be6eaa0ee5c66431a71cbfdd839779ccf29e4c2/worker/src/response.rs#L164-L168

### PR DESCRIPTION
**Pull request by kiwiyou**
This fixes #80.

### CODE REVIEW

**Comment by nilslice** [comment]
Hi @kiwiyou - thanks for this! Would you mind sharing how you are constructing the request which triggers this branch? using `curl` would be ideal, but if you have another way already that would be great too.

**Comment by kiwiyou** [comment]
When I sent a request to https://static.solved.ac/misc/default_profile.png (CDN server of other person) worker-rs retrieves the body well. However, when I used `CfProperties` to set `cache_everything` on, `Called .text() on an HTTP body which does not appear to be text.` message appeared and the image did not render properly.

**Comment by nilslice** [comment]
Hi @kiwiyou  - thank you for the follow-up. If you are ready for this to be reviewed, please update from Draft to normal PR. No rush, I just didn't want you to think it's blocked on anything else. 

I haven't taken a close look, thinking you are still working on some aspects of it. But if it's ready, I'm happy to put it in my review rotation. Thanks!

**Comment by nilslice** [comment]
Thank you!

**Pull request merged**
