### PR TITLE
Add R2 support

### PR DESCRIPTION
**Pull request by zebp**

### CODE REVIEW

**Comment by zebp** [comment]
This is mostly finished, the only problem with it currently is R2 puts only allow a stream of a known length. Currently this is done by using a FixedLengthStream or a request/response body. This is probably blocked until FixedLengthStream is implemented.

**Comment by schoenenberg** [comment]
It looks like `FixedLengthStream` is also implemented. What is missing to get this merged?

**Comment by zebp** [comment]
> It looks like `FixedLengthStream` is also implemented. What is missing to get this merged?

Just testing against workerd, I've been preoccupied with other things and US holidays so I haven't gotten a chance yet. I hope to have this merged and released this upcoming week.

**Comment by DerZade** [comment]
Would love this 🎉

What is the hold up on this? Is there anything I can do to move this forward?

**Comment by HurricanKai** [comment]
Would love to see this happen!

Could it make sense to allow a separate `.into_body()` on `Object`? This would allow better ergonomics with `Option::and_then` and it's the intended way of using the type in JS anyways, right?

**Comment by jakubadamw** [comment]
It would be really great to see this go in! 🙂 Anything one could do to help?

**Comment by zebp** [comment]
Sadly not, I've been super swamped with other things so I haven't been able to circle back on this yet. I rebased it earlier this week, should just need testing against the production workerd runtime.

**Comment by jakubadamw** [comment]
@zebp I noticed this PR does not include support for [multipart uploads](https://developers.cloudflare.com/r2/data-access/workers-api/workers-api-reference/#r2multipartupload-definition) (which would be great to have for the sake of 1:1 feature equivalence), so I went ahead and implemented that in [this branch](https://github.com/jakubadamw/workers-rs/tree/r2-multipart-uploads). I will open a PR once this goes in. 🙂

**Comment by geekyayush** [comment]
When is it going to be released?
I really need it right now 😅

**Comment by DerZade** [comment]
> When is it going to be released? I really need it right now 😅

Would love this as well.

@geekyayush If you want to start developing against the new API, you can use it today as follows:

```toml
[dependencies]
worker = { git = "https://github.com/cloudflare/workers-rs", branch = "main" }
```
— see [here](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) in the documentation

**Pull request merged**
